# Generated by Django 6.1 on 2026-08-30 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitors', '0002_checkresult_incident_processed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=16)),
                ('started_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('failure_type', models.CharField(choices=[('TIMEOUT', 'Timeout'), ('DNS_ERROR', 'DNS error'), ('CONNECTION_ERROR', 'Connection error'), ('TLS_ERROR', 'TLS error'), ('HTTP_ERROR', 'HTTP error'), ('TOO_MANY_REDIRECTS', 'Too many redirects'), ('BLOCKED_TARGET', 'Blocked target'), ('UNKNOWN_ERROR', 'Unknown error')], max_length=32)),
                ('initial_error_message', models.CharField(blank=True, max_length=500, null=True)),
                ('latest_error_message', models.CharField(blank=True, max_length=500, null=True)),
                ('initial_status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('latest_status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('recovery_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='monitors.monitor')),
            ],
            options={
                'ordering': ('-started_at', '-id'),
                'indexes': [models.Index(fields=['monitor', '-started_at'], name='incident_monitor_started'), models.Index(fields=['status', '-started_at'], name='incident_status_started')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('monitor',), name='unique_open_incident_per_monitor')],
            },
        ),
    ]
