# Generated by Django 6.1 on 2026-08-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='failure_type',
            field=models.CharField(choices=[('TIMEOUT', 'Timeout'), ('DNS_ERROR', 'DNS error'), ('CONNECTION_ERROR', 'Connection error'), ('TLS_ERROR', 'TLS error'), ('HTTP_ERROR', 'HTTP error'), ('TOO_MANY_REDIRECTS', 'Too many redirects'), ('BLOCKED_TARGET', 'Blocked target'), ('BROWSER_TIMEOUT', 'Browser timeout'), ('NAVIGATION_ERROR', 'Navigation error'), ('EXPECTED_TEXT_MISSING', 'Expected text missing'), ('EXPECTED_SELECTOR_MISSING', 'Expected selector missing'), ('BROWSER_ERROR', 'Browser error'), ('UNKNOWN_ERROR', 'Unknown error')], max_length=32),
        ),
    ]
