# Generated by Django 6.1 on 2026-08-30 17:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_type', models.CharField(choices=[('HTTP', 'HTTP')], default='HTTP', max_length=16)),
                ('is_enabled', models.BooleanField(default=True)),
                ('interval_seconds', models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(86400)])),
                ('timeout_seconds', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='websites.website')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_success', models.BooleanField()),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_type', models.CharField(blank=True, choices=[('TIMEOUT', 'Timeout'), ('DNS_ERROR', 'DNS error'), ('CONNECTION_ERROR', 'Connection error'), ('TLS_ERROR', 'TLS error'), ('HTTP_ERROR', 'HTTP error'), ('TOO_MANY_REDIRECTS', 'Too many redirects'), ('BLOCKED_TARGET', 'Blocked target'), ('UNKNOWN_ERROR', 'Unknown error')], max_length=32, null=True)),
                ('error_message', models.CharField(blank=True, max_length=500, null=True)),
                ('ssl_expires_at', models.DateTimeField(blank=True, null=True)),
                ('ssl_days_remaining', models.IntegerField(blank=True, null=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='monitors.monitor')),
            ],
            options={
                'ordering': ('-checked_at', '-id'),
                'indexes': [models.Index(fields=['monitor', '-checked_at'], name='checkresult_monitor_time'), models.Index(fields=['is_success', '-checked_at'], name='checkresult_success_time')],
            },
        ),
    ]
