# Generated by Django 6.1 on 2026-08-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkresult',
            name='incident_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
