# Generated by Django 6.1 on 2026-08-30 19:09

import monitors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0002_checkresult_incident_processed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkresult',
            name='final_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='checkresult',
            name='screenshot',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=monitors.models.screenshot_path),
        ),
        migrations.AddField(
            model_name='monitor',
            name='expected_selector',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='expected_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='checkresult',
            name='error_type',
            field=models.CharField(blank=True, choices=[('TIMEOUT', 'Timeout'), ('DNS_ERROR', 'DNS error'), ('CONNECTION_ERROR', 'Connection error'), ('TLS_ERROR', 'TLS error'), ('HTTP_ERROR', 'HTTP error'), ('TOO_MANY_REDIRECTS', 'Too many redirects'), ('BLOCKED_TARGET', 'Blocked target'), ('BROWSER_TIMEOUT', 'Browser timeout'), ('NAVIGATION_ERROR', 'Navigation error'), ('EXPECTED_TEXT_MISSING', 'Expected text missing'), ('EXPECTED_SELECTOR_MISSING', 'Expected selector missing'), ('BROWSER_ERROR', 'Browser error'), ('UNKNOWN_ERROR', 'Unknown error')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='monitor_type',
            field=models.CharField(choices=[('HTTP', 'HTTP'), ('BROWSER', 'Browser')], default='HTTP', max_length=16),
        ),
    ]
