# Generated by Django 6.1 on 2026-08-30 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0003_checkresult_final_url_checkresult_screenshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkresult',
            name='error_type',
            field=models.CharField(blank=True, choices=[('TIMEOUT', 'Timeout'), ('DNS_ERROR', 'DNS error'), ('CONNECTION_ERROR', 'Connection error'), ('TLS_ERROR', 'TLS error'), ('HTTP_ERROR', 'HTTP error'), ('TOO_MANY_REDIRECTS', 'Too many redirects'), ('BLOCKED_TARGET', 'Blocked target'), ('BROWSER_TIMEOUT', 'Browser timeout'), ('NAVIGATION_ERROR', 'Navigation error'), ('EXPECTED_TEXT_MISSING', 'Expected text missing'), ('EXPECTED_SELECTOR_MISSING', 'Expected selector missing'), ('BROWSER_ERROR', 'Browser error'), ('FLOW_CONFIGURATION_ERROR', 'Flow configuration error'), ('FLOW_FIELD_NOT_FOUND', 'Flow field not found'), ('FLOW_FIELD_INTERACTION_ERROR', 'Flow field interaction error'), ('FLOW_SUBMIT_NOT_FOUND', 'Flow submit control not found'), ('FLOW_SUBMIT_ERROR', 'Flow submit error'), ('FLOW_TIMEOUT', 'Flow timeout'), ('FLOW_SUCCESS_TEXT_MISSING', 'Flow success text missing'), ('FLOW_SUCCESS_SELECTOR_MISSING', 'Flow success selector missing'), ('FLOW_SUCCESS_URL_MISMATCH', 'Flow success URL mismatch'), ('UNKNOWN_ERROR', 'Unknown error')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='monitor_type',
            field=models.CharField(choices=[('HTTP', 'HTTP'), ('BROWSER', 'Browser'), ('FLOW', 'Flow')], default='HTTP', max_length=16),
        ),
        migrations.CreateModel(
            name='FlowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_kind', models.CharField(choices=[('CONTACT_FORM', 'Contact form')], max_length=32)),
                ('submit_selector', models.CharField(max_length=500)),
                ('success_text', models.CharField(blank=True, max_length=200, null=True)),
                ('success_selector', models.CharField(blank=True, max_length=500, null=True)),
                ('success_url_contains', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flow_config', to='monitors.monitor')),
            ],
        ),
        migrations.CreateModel(
            name='FlowField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector', models.CharField(max_length=500)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('EMAIL', 'Email'), ('TEXTAREA', 'Textarea'), ('CHECKBOX', 'Checkbox'), ('SELECT', 'Select')], default='TEXT', max_length=16)),
                ('value', models.CharField(blank=True, max_length=1000)),
                ('position', models.PositiveIntegerField(default=0)),
                ('flow_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='monitors.flowconfig')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='flowconfig',
            constraint=models.CheckConstraint(condition=models.Q(('success_text__isnull', False), ('success_selector__isnull', False), ('success_url_contains__isnull', False), _connector='OR'), name='flowconfig_requires_a_success_assertion'),
        ),
    ]
