# Generated by Django 6.1 on 2026-08-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0004_alter_checkresult_error_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkresult',
            name='error_type',
            field=models.CharField(blank=True, choices=[('TIMEOUT', 'Timeout'), ('DNS_ERROR', 'DNS error'), ('CONNECTION_ERROR', 'Connection error'), ('TLS_ERROR', 'TLS error'), ('HTTP_ERROR', 'HTTP error'), ('TOO_MANY_REDIRECTS', 'Too many redirects'), ('BLOCKED_TARGET', 'Blocked target'), ('BROWSER_TIMEOUT', 'Browser timeout'), ('NAVIGATION_ERROR', 'Navigation error'), ('EXPECTED_TEXT_MISSING', 'Expected text missing'), ('EXPECTED_SELECTOR_MISSING', 'Expected selector missing'), ('BROWSER_ERROR', 'Browser error'), ('FLOW_CONFIGURATION_ERROR', 'Flow configuration error'), ('FLOW_FIELD_NOT_FOUND', 'Flow field not found'), ('FLOW_FIELD_INTERACTION_ERROR', 'Flow field interaction error'), ('FLOW_SUBMIT_NOT_FOUND', 'Flow submit control not found'), ('FLOW_SUBMIT_ERROR', 'Flow submit error'), ('FLOW_TIMEOUT', 'Flow timeout'), ('FLOW_SUCCESS_TEXT_MISSING', 'Flow success text missing'), ('FLOW_SUCCESS_SELECTOR_MISSING', 'Flow success selector missing'), ('FLOW_SUCCESS_URL_MISMATCH', 'Flow success URL mismatch'), ('FLOW_DESTINATION_NOT_ALLOWED', 'Flow submission destination not allowed'), ('UNKNOWN_ERROR', 'Unknown error')], max_length=32, null=True),
        ),
    ]
