# Generated by Django 6.1 on 2026-08-31 10:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0005_alter_checkresult_error_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='last_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='next_check_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='MonitorRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED_INTERNAL', 'Failed internally'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('claim_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('internal_error', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='monitors.checkresult')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='monitors.monitor')),
            ],
            options={
                'ordering': ('-scheduled_for', '-created_at'),
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='monitorrun_status_slot'), models.Index(fields=['monitor', '-scheduled_for'], name='monitorrun_monitor_slot')],
                'constraints': [models.UniqueConstraint(fields=('monitor', 'scheduled_for'), name='monitorrun_unique_slot')],
            },
        ),
    ]
