# Generated by Django 6.1 on 2026-08-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0006_monitor_last_scheduled_at_monitor_next_check_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorrun',
            name='recovery_enqueued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
