# Generated by Django 6.1 on 2026-08-31 11:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0004_alter_incident_failure_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('INCIDENT_OPENED', 'Incident opened'), ('INCIDENT_RESOLVED', 'Incident resolved')], max_length=32)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_events', to='incidents.incident')),
            ],
            options={
                'ordering': ('-occurred_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email')], default='EMAIL', max_length=16)),
                ('recipient', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('claim_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('enqueued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notificationevent')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('alert_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['event_type', '-occurred_at'], name='notifevent_type_time'),
        ),
        migrations.AddConstraint(
            model_name='notificationevent',
            constraint=models.UniqueConstraint(fields=('incident', 'event_type'), name='notificationevent_unique_transition'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='notifdelivery_status_due'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(fields=('event', 'channel', 'recipient'), name='notificationdelivery_unique_target'),
        ),
    ]
