# Generated by Django 6.1 on 2026-08-31 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_alter_incident_failure_type'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notificationevent',
            name='notificationevent_unique_transition',
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='failure_summary',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='failure_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='has_evidence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='incident_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='incident_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='monitor_ref',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='monitor_type',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='status_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='website_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='website_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_events', to='incidents.incident'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['monitor_ref', '-occurred_at'], name='notifevent_monitor_time'),
        ),
        migrations.AddConstraint(
            model_name='notificationevent',
            constraint=models.UniqueConstraint(fields=('monitor_ref', 'event_type', 'incident_started_at'), name='notificationevent_unique_outage_transition'),
        ),
    ]
